id: I20BBAA05
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T10:12:21+00:00'
last_modified: '2022-06-15T17:32:06.464139+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24357
  title: བོད་ཤོག་བཟོ་རྩལ་མྱུར་སྐྱོབ་དང་འཕེལ་རྒྱས་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    EAA6:
      image_group_id: I1KG24457
      title: Volume 1 of
      total_pages: 232
      order: 1
      base_file: EAA6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
