id: P000373
initial_creation_type: ocr
created_at: 17/03/2020
last_modified_at: 2021-12-16 15:36:38.245575
source_metadata:
  id: bdr:W1KG24357
  title: བོད་ཤོག་བཟོ་རྩལ་མྱུར་སྐྱོབ་དང་འཕེལ་རྒྱས་སྐོར།
  author: ''
  volumes:
    17f702df70854c66a078a790d0e5aa61:
      image_group_id: I1KG24457
      title: Volume 1 of
      volume_number: 1
      total_pages: 232
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
